#!/bin/bash

# script generated by chatgpt
folder_path="."

# Check if ImageMagick is installed
if ! command -v convert &> /dev/null; then
    echo "ImageMagick is not installed. Please install it first."
    exit 1
fi

# Change directory to the specified folder path
cd "$folder_path" || exit 1

# Loop through each GIF file in the folder
for gif_file in *.gif; do
    # Extract the filename without the extension
    filename="${gif_file%.*}"
    
    # Convert GIF to PNG using ImageMagick
    convert "$gif_file" "${filename}.png"
    
    rm "$gif_file"
done

echo "Conversion complete!"
